version: "3.9"
services:
  aparts:
    build: .
    env_file:
      - aparts.env
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    volumes:
      - redis_data:/data
volumes:
  redis_data: