version: "3.9"
services:
  aparts:
    build: .
    environment:
      - BOT_API_KEY=
      - CHAT_ID=
      - CITY=
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    volumes:
      - redis_data:/data
volumes:
  redis_data: